**Working with torch**

In [ ]:
import torch

In [ ]:
x = torch.ones(3,2,requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
x = torch.randn(3,2,requires_grad=True)
print(x)
x.view(2,3)

tensor([[ 1.2015, -0.8402],
        [ 1.1690,  1.8421],
        [ 0.2069, -0.2384]], requires_grad=True)


tensor([[ 1.2015, -0.8402,  1.1690],
        [ 1.8421,  0.2069, -0.2384]], grad_fn=<ViewBackward0>)

In [ ]:
x = torch.empty(3,2,requires_grad=True)
print(x)

tensor([[1.6922e-24, 4.4617e-41],
        [1.6922e-24, 4.4617e-41],
        [4.4842e-44, 0.0000e+00]], requires_grad=True)


In [ ]:
x = torch.linspace(1,10,5,requires_grad=True)
print(x)
x.size()

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000], requires_grad=True)


torch.Size([5])

In [ ]:
# x[:,1],x[1,1].item()

In [ ]:
x = torch.rand(3,2,requires_grad=True)
y = torch.rand(3,2,requires_grad=True)
print(x+y)
print(x*y)
print(x@y.T)

tensor([[0.2582, 1.2976],
        [1.6528, 0.1903],
        [1.3796, 1.1606]], grad_fn=<AddBackward0>)
tensor([[0.0119, 0.3944],
        [0.6815, 0.0090],
        [0.4285, 0.2574]], grad_fn=<MulBackward0>)
tensor([[0.4063, 0.1213, 0.7544],
        [0.2194, 0.6905, 0.8704],
        [0.2385, 0.3992, 0.6858]], grad_fn=<MmBackward0>)


In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(torch.from_numpy(a))

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
torch.cuda.device_count()

1

In [ ]:
cuda0 = torch.cuda.get_device_name(0)
cuda0

'Tesla T4'

In [ ]:
a = torch.ones(3,2, device = 'cuda')
print(a)
b = torch.rand(3,2, device = 'cuda')
print(b)
print(a+b)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], device='cuda:0')
tensor([[0.3833, 0.0962],
        [0.5183, 0.4519],
        [0.5969, 0.8786]], device='cuda:0')
tensor([[1.3833, 1.0962],
        [1.5183, 1.4519],
        [1.5969, 1.8786]], device='cuda:0')


In [ ]:
%%timeit
a = torch.ones(3,2, device = 'cuda')
b = torch.rand(3,2, device = 'cuda')
c = a@b.T

The slowest run took 313.22 times longer than the fastest. This could mean that an intermediate result is being cached.
4.92 ms ± 7.63 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit
for i in range(100):
  a = torch.ones(10,2, device = 'cuda')
  b = torch.rand(3,2, device = 'cuda')
  c = a@b.T

6.01 ms ± 1.12 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
import sympy as sp
x = sp.symbols('x')
y = sp.symbols('y')
z = sp.symbols('z')

y = x**2 + 1
sp.diff(2*y**3 +3*y +5,x)

12*x*(x**2 + 1)**2 + 6*x

In [ ]:
#Auto differentiation

x = torch.ones(3,2,requires_grad=True)
y = x+5
y

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)

In [ ]:
z = y*y +3
z

tensor([[39., 39.],
        [39., 39.],
        [39., 39.]], grad_fn=<AddBackward0>)

In [ ]:
t = torch.sum(z)
t

tensor(234., grad_fn=<SumBackward0>)

In [ ]:
t.backward()
x.grad

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])

In [ ]:
x = torch.randn(3,2,requires_grad=True)
y = 3*x+5
y

tensor([[4.1113, 5.5409],
        [0.7981, 2.0032],
        [4.2665, 4.9845]], grad_fn=<AddBackward0>)

In [ ]:
x = torch.rand(20,1,requires_grad=True)
y = 3*x-2

In [ ]:
from logging import logProcesses
w = torch.tensor([1.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)
y_hat = w*x + b
los = torch.sum((y-y_hat)**2)
los.backward()

In [ ]:
print(w.grad)
print(b.grad)

tensor([39.0622])
tensor([69.9267])
